import { createClient } from "npm:@supabase/supabase-js@2";
const URL=Deno.env.get("SUPABASE_URL")!;
const SERVICE=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") || Deno.env.get("SUPABASE_SECRET_KEY")!;
const PUBLISHABLE=Deno.env.get("SUPABASE_ANON_KEY") || Deno.env.get("SUPABASE_PUBLISHABLE_KEY")!;
const ALLOWED_ORIGIN=(Deno.env.get("EDUTEST_ALLOWED_ORIGIN")||"").replace(/\/$/,"");
const cors={"Access-Control-Allow-Origin":ALLOWED_ORIGIN,"Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS","Vary":"Origin"};
const json=(body:any,status=200)=>new Response(JSON.stringify(body),{status,headers:{...cors,"Content-Type":"application/json"}});
function adminClient(){return createClient(URL,SERVICE,{auth:{persistSession:false,autoRefreshToken:false}});}
async function caller(req:Request){
 const auth=req.headers.get("Authorization")||""; if(!auth.startsWith("Bearer "))throw new Error("AUTH_REQUIRED");
 const c=createClient(URL,PUBLISHABLE,{global:{headers:{Authorization:auth}},auth:{persistSession:false,autoRefreshToken:false}});
 const {data,error}=await c.auth.getUser(); if(error||!data.user)throw new Error("AUTH_REQUIRED"); return data.user;
}
function under16(dob:string|null){if(!dob)return false;const d=new Date(dob+'T00:00:00Z'),n=new Date();let a=n.getUTCFullYear()-d.getUTCFullYear();const m=n.getUTCMonth()-d.getUTCMonth();if(m<0||(m===0&&n.getUTCDate()<d.getUTCDate()))a--;return a<16;}
async function profileGate(db:any,userId:string){const {data:p,error}=await db.from('profiles').select('id,email,name,role,grade,birth_date,guardian_verified_at').eq('id',userId).single();if(error||!p)throw new Error('PROFILE_REQUIRED');if(p.role==='student'){if(!p.birth_date)throw new Error('AGE_VERIFICATION_REQUIRED');if(under16(p.birth_date)&&!p.guardian_verified_at)throw new Error('GUARDIAN_CONSENT_REQUIRED');}return p;}
function shuffle<T>(a:T[]){const x=[...a];for(let i=x.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[x[i],x[j]]=[x[j],x[i]];}return x;}

async function requireTeacher(db:any,userId:string){const {data:p,error}=await db.from('profiles').select('id,email,name,role,grade').eq('id',userId).single();if(error||!p||!['teacher','admin'].includes(p.role))throw new Error('TEACHER_REQUIRED');return p;}
const testDto=(t:any)=>({id:t.id,title:t.title,subject:t.subject,grade:t.grade,pool:t.pool_prefix||('custom:'+t.id),count:t.question_count,time:t.time_minutes,attempts:t.attempts,paid:t.paid,semester:t.semester,testType:t.test_type,sumTest:t.is_summary,serverCustom:!!t.owner_user_id,audienceGrade:t.audience_grade,dueAt:t.due_at});
Deno.serve(async(req)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});if(req.method!=='POST')return json({error:'METHOD_NOT_ALLOWED'},405);if(!ALLOWED_ORIGIN)return json({error:'SERVER_ORIGIN_NOT_CONFIGURED'},503);const declared=Number(req.headers.get('content-length')||0);if(declared>131072)return json({error:'PAYLOAD_TOO_LARGE'},413);try{const user=await caller(req),db=adminClient();const body=await req.json();const action=String(body.action||'');
 if(action==='my_assignments'){const p=await profileGate(db,user.id);if(p.role!=='student')return json({tests:[]});let q=db.from('assessment_tests').select('*').not('owner_user_id','is',null).eq('published',true);const {data,error}=await q;if(error)throw error;const now=Date.now();return json({tests:(data||[]).filter((t:any)=>(!t.audience_grade||String(t.audience_grade)===String(p.grade))&&(!t.due_at||new Date(t.due_at).getTime()>=now)).map(testDto)});}
 const p=await requireTeacher(db,user.id);
 if(action==='catalog'){let q=db.from('assessment_questions').select('id,grade,subject,semester,topic,question_type,points,public_payload').eq('active',true).eq('grade',Number(body.grade)).eq('subject',String(body.subject||''));if(body.semester)q=q.eq('semester',Number(body.semester));const {data,error}=await q.limit(300);if(error)throw error;return json({questions:(data||[]).map((x:any)=>({id:x.id,text:x.public_payload?.text||x.id,type:x.question_type,topic:x.topic,semester:x.semester,pts:x.points}))});}
 if(action==='create'){const ids=Array.isArray(body.question_ids)?[...new Set(body.question_ids.map(String))]:[];if(!ids.length||ids.length>100)return json({error:'Select 1-100 questions'},400);const grade=Number(body.grade);const subject=String(body.subject||'');const {data:qrows,error:qe}=await db.from('assessment_questions').select('id,grade,subject').in('id',ids).eq('active',true);if(qe)throw qe;if((qrows||[]).length!==ids.length||qrows.some((q:any)=>q.grade!==grade||q.subject!==subject))return json({error:'Question selection does not match grade/subject'},400);const id='custom-'+crypto.randomUUID();const row={id,title:String(body.title||'Custom test').slice(0,160),subject,grade,pool_prefix:null,question_count:ids.length,time_minutes:Math.max(1,Math.min(240,Number(body.time||20))),attempts:Math.max(1,Math.min(20,Number(body.attempts||2))),paid:false,semester:body.semester?Number(body.semester):null,test_type:'custom',is_summary:false,owner_user_id:user.id,audience_grade:String(body.audience_grade||'').trim()||null,due_at:body.due_at||null,published:body.published!==false,reveal_answers:!!body.reveal_answers};const {error}=await db.from('assessment_tests').insert(row);if(error)throw error;const links=ids.map((qid:string,i:number)=>({test_id:id,question_id:qid,position:i}));const {error:le}=await db.from('assessment_test_questions').insert(links);if(le)throw le;return json({test:testDto(row)});}
 if(action==='list_mine'){let q=db.from('assessment_tests').select('*').eq('owner_user_id',user.id).order('created_at',{ascending:false});if(p.role==='admin'&&body.all===true)q=db.from('assessment_tests').select('*').not('owner_user_id','is',null).order('created_at',{ascending:false});const {data,error}=await q;if(error)throw error;return json({tests:(data||[]).map(testDto)});}
 if(action==='delete'){const id=String(body.test_id||'');let q=db.from('assessment_tests').delete().eq('id',id);if(p.role!=='admin')q=q.eq('owner_user_id',user.id);const {error}=await q;if(error)throw error;return json({ok:true});}
 if(action==='verified_results'){let testIds:string[]=[];if(p.role==='admin'){const {data}=await db.from('assessment_tests').select('id').not('owner_user_id','is',null);testIds=(data||[]).map((x:any)=>x.id);}else{const {data}=await db.from('assessment_tests').select('id').eq('owner_user_id',user.id);testIds=(data||[]).map((x:any)=>x.id);}if(!testIds.length)return json({results:[]});const {data:rs,error}=await db.from('assessment_results').select('*').in('test_id',testIds).eq('verified',true).order('submitted_at',{ascending:false}).limit(2000);if(error)throw error;const uids=[...new Set((rs||[]).map((r:any)=>r.user_id))];let profs:any[]=[];if(uids.length){const {data}=await db.from('profiles').select('id,email,name,grade').in('id',uids);profs=data||[];}const pm=new Map(profs.map((x:any)=>[x.id,x]));return json({results:(rs||[]).map((r:any)=>{const u=pm.get(r.user_id)||{};return{userId:u.email||r.user_id,userName:u.name||'',userGrade:u.grade||'',testId:r.test_id,earned:Number(r.earned),totalPts:Number(r.total_points),correct:r.correct_count,total:r.total_questions,pct:r.pct,verified:true,date:new Date(r.submitted_at).toLocaleDateString('ka-GE'),reviewed:r.review_summary||[]};})});}
 return json({error:'Unknown action'},400);
}catch(e){const m=String(e?.message||e);return json({error:m},m==='AUTH_REQUIRED'?401:m==='TEACHER_REQUIRED'?403:500);}});
