import { createClient } from "npm:@supabase/supabase-js@2";
const URL=Deno.env.get("SUPABASE_URL")!;
const SERVICE=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") || Deno.env.get("SUPABASE_SECRET_KEY")!;
const PUBLISHABLE=Deno.env.get("SUPABASE_ANON_KEY") || Deno.env.get("SUPABASE_PUBLISHABLE_KEY")!;
const ALLOWED_ORIGIN=(Deno.env.get("EDUTEST_ALLOWED_ORIGIN")||"").replace(/\/$/,"");
const cors={"Access-Control-Allow-Origin":ALLOWED_ORIGIN,"Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS","Vary":"Origin"};
const json=(body:any,status=200)=>new Response(JSON.stringify(body),{status,headers:{...cors,"Content-Type":"application/json"}});
function adminClient(){return createClient(URL,SERVICE,{auth:{persistSession:false,autoRefreshToken:false}});}
async function caller(req:Request){
 const auth=req.headers.get("Authorization")||""; if(!auth.startsWith("Bearer "))throw new Error("AUTH_REQUIRED");
 const c=createClient(URL,PUBLISHABLE,{global:{headers:{Authorization:auth}},auth:{persistSession:false,autoRefreshToken:false}});
 const {data,error}=await c.auth.getUser(); if(error||!data.user)throw new Error("AUTH_REQUIRED"); return data.user;
}
function under16(dob:string|null){if(!dob)return false;const d=new Date(dob+'T00:00:00Z'),n=new Date();let a=n.getUTCFullYear()-d.getUTCFullYear();const m=n.getUTCMonth()-d.getUTCMonth();if(m<0||(m===0&&n.getUTCDate()<d.getUTCDate()))a--;return a<16;}
async function profileGate(db:any,userId:string){const {data:p,error}=await db.from('profiles').select('id,email,name,role,grade,birth_date,guardian_verified_at').eq('id',userId).single();if(error||!p)throw new Error('PROFILE_REQUIRED');if(p.role==='student'){if(!p.birth_date)throw new Error('AGE_VERIFICATION_REQUIRED');if(under16(p.birth_date)&&!p.guardian_verified_at)throw new Error('GUARDIAN_CONSENT_REQUIRED');}return p;}
function shuffle<T>(a:T[]){const x=[...a];for(let i=x.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[x[i],x[j]]=[x[j],x[i]];}return x;}

const norm=(x:any)=>String(x??'').trim().toLocaleLowerCase('ka-GE');
function grade(q:any,ua:any){const k=q.answer_key||{},t=q.question_type;if(t==='multiple_choice'||t==='true_false')return Number(ua)===Number(k.correct);if(t==='calc'){const n=Number(ua),a=Number(k.correct),tol=Number(k.tolerance||0);return Number.isFinite(n)&&Number.isFinite(a)&&Math.abs(n-a)<=tol;}if(t==='order')return Array.isArray(ua)&&Array.isArray(k.correct)&&ua.length===k.correct.length&&ua.every((v:any,i:number)=>String(v)===String(k.correct[i]));if(t==='match'){if(!ua||typeof ua!=='object'||!Array.isArray(k.correct))return false;return k.correct.every((v:any,i:number)=>String(ua[i]??ua[String(i)]??'')===String(v));}if(t==='fill'){return Array.isArray(ua)&&Array.isArray(k.blanks)&&ua.length===k.blanks.length&&k.blanks.every((v:any,i:number)=>norm(ua[i])===norm(v));}return false;}
function revealReview(q:any,ua:any,ok:boolean,reveal:boolean){const p=q.public_payload||{};const r:any={id:q.id,text:p.text,type:q.question_type,pts:q.points,ua,ok,topic:q.topic||p.topic||'',reveal};if(reveal){r.explain=q.explanation||'';if(q.question_type==='multiple_choice'||q.question_type==='true_false'){r.opts=p.opts||[];r.correct=q.answer_key?.correct;}else if(q.question_type==='calc'){r.correct=q.answer_key?.correct;r.tolerance=q.answer_key?.tolerance||0;}else if(q.question_type==='order'){r.correct=q.answer_key?.correct||[];}else if(q.question_type==='match'){r.pairs=q.answer_key?.pairs||[];r.correct=q.answer_key?.correct||[];}else if(q.question_type==='fill'){r.blanks=q.answer_key?.blanks||[];}}return r;}
Deno.serve(async(req)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});if(req.method!=='POST')return json({error:'METHOD_NOT_ALLOWED'},405);if(!ALLOWED_ORIGIN)return json({error:'SERVER_ORIGIN_NOT_CONFIGURED'},503);const declared=Number(req.headers.get('content-length')||0);if(declared>131072)return json({error:'PAYLOAD_TOO_LARGE'},413);try{
 const user=await caller(req),db=adminClient();await profileGate(db,user.id);const body=await req.json();const sid=String(body.session_id||'');const answers=body.answers&&typeof body.answers==='object'?body.answers:{};if(!sid)return json({error:'session_id required'},400);
 const {data:s,error:se}=await db.from('assessment_sessions').select('*').eq('id',sid).eq('user_id',user.id).single();if(se||!s)return json({error:'SESSION_NOT_FOUND'},404);if(s.status!=='active'||s.submitted_at)return json({error:'SESSION_ALREADY_SUBMITTED'},409);if(new Date(s.expires_at).getTime()+60000<Date.now())return json({error:'SESSION_EXPIRED'},409);
 const {data:test,error:te}=await db.from('assessment_tests').select('*').eq('id',s.test_id).single();if(te||!test)throw te||new Error('TEST_NOT_FOUND');const {data:qrows,error:qe}=await db.from('assessment_questions').select('*').in('id',s.question_ids);if(qe)throw qe;const qm=new Map((qrows||[]).map((q:any)=>[q.id,q]));const ordered=s.question_ids.map((id:string)=>qm.get(id)).filter(Boolean);
 let earned=0,total=0,correct=0;const results:any[]=[];for(const q of ordered){total+=Number(q.points||1);const ua=answers[q.id]??null;const ok=grade(q,ua);if(ok){earned+=Number(q.points||1);correct++;}results.push({q,ua,ok});}
 const pct=total?Math.round(earned/total*100):0;const reveal=s.mode==='practice'||!!test.reveal_answers;const review=results.map(x=>revealReview(x.q,x.ua,x.ok,reveal));
 const {error:re}=await db.from('assessment_results').insert({session_id:s.id,user_id:user.id,test_id:s.test_id,earned,total_points:total,correct_count:correct,total_questions:ordered.length,pct,verified:true,student_answers:answers,review_summary:review});if(re)throw re;
 await db.from('assessment_sessions').update({status:'submitted',submitted_at:new Date().toISOString(),integrity:{...(s.integrity||{}),tab_switch_count:Number(body.tab_switch_count||0),graded:'server'}}).eq('id',s.id).eq('user_id',user.id);
 // Authoritative history counters: browser can no longer write these tables.
 const {data:oldH}=await db.from('question_history').select('*').eq('user_id',user.id).in('question_id',s.question_ids);const hm=new Map((oldH||[]).map((h:any)=>[h.question_id,h]));const now=new Date().toISOString();const hrows=results.map(x=>{const h=hm.get(x.q.id)||{};return{user_id:user.id,question_id:x.q.id,seen_count:Number(h.seen_count||0)+1,correct_count:Number(h.correct_count||0)+(x.ok?1:0),wrong_count:Number(h.wrong_count||0)+(x.ok?0:1),last_seen:now,last_correct:x.ok?now:(h.last_correct||null),last_wrong:x.ok?(h.last_wrong||null):now,last_test_id:s.test_id,last_pool:test.pool_prefix||('custom:'+s.test_id)};});if(hrows.length){const {error}=await db.from('question_history').upsert(hrows,{onConflict:'user_id,question_id'});if(error)throw error;}
 const pool=test.pool_prefix||('custom:'+s.test_id);const {data:sp}=await db.from('subject_history').select('*').eq('user_id',user.id).eq('pool_key',pool).maybeSingle();const diff0=Number(sp?.diff??1),diff=pct>=85?Math.min(2,diff0+1):pct<50?Math.max(0,diff0-1):diff0;const {error:spe}=await db.from('subject_history').upsert({user_id:user.id,pool_key:pool,sessions:Number(sp?.sessions||0)+1,total_pct:Number(sp?.total_pct||0)+pct,diff,last_session_at:now},{onConflict:'user_id,pool_key'});if(spe)throw spe;
 return json({result:{sessionId:s.id,testId:s.test_id,title:test.title,subject:test.subject,grade:test.grade,earned,totalPts:total,correct,total:ordered.length,pct,verified:true,mode:s.mode,date:new Date().toLocaleDateString('ka-GE')},review});
}catch(e){const m=String(e?.message||e);return json({error:m},m==='AUTH_REQUIRED'?401:500);}});
