-- EduTest.ge — Supabase child-safety & privacy-by-design migration
-- Date: 2026-08-09
-- Run in Supabase SQL Editor AFTER / instead of the prior EduTest-Supabase-Setup.sql.
-- Browser code must use ONLY the publishable key. Never expose a secret/service-role key.

begin;

-- 1) Profiles: add age/consent/privacy state and privacy-by-default settings.
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  name text not null default '',
  role text not null default 'student',
  grade text not null default '',
  school text not null default '',
  premium boolean not null default false,
  paid_subjects text[] not null default '{}'::text[],
  join_date timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.profiles add column if not exists birth_date date;
alter table public.profiles add column if not exists guardian_email text;
alter table public.profiles add column if not exists guardian_verified_at timestamptz;
alter table public.profiles add column if not exists terms_version text;
alter table public.profiles add column if not exists terms_accepted_at timestamptz;
alter table public.profiles add column if not exists privacy_version text;
alter table public.profiles add column if not exists privacy_acknowledged_at timestamptz;
alter table public.profiles add column if not exists leaderboard_opt_in boolean not null default false;
alter table public.profiles add column if not exists last_active_at timestamptz not null default now();
alter table public.profiles add column if not exists deletion_requested_at timestamptz;

alter table public.profiles drop constraint if exists profiles_role_check;
alter table public.profiles add constraint profiles_role_check
  check (role in ('student','pending_teacher','teacher','admin','guardian'));

alter table public.profiles enable row level security;

drop policy if exists "profiles_select_own" on public.profiles;
create policy "profiles_select_own" on public.profiles
for select to authenticated using (auth.uid() = id);

drop policy if exists "profiles_update_own" on public.profiles;
create policy "profiles_update_own" on public.profiles
for update to authenticated
using (auth.uid() = id) with check (auth.uid() = id);

revoke all on table public.profiles from anon, authenticated;
grant select on table public.profiles to authenticated;
-- Users may edit ordinary profile fields only. Role, premium, consent verification and deletion state are server-controlled.
grant update (name, grade, school, leaderboard_opt_in, last_active_at) on table public.profiles to authenticated;

-- 2) Guardian consent requests and immutable audit log.
create table if not exists public.guardian_consent_requests (
  id uuid primary key default gen_random_uuid(),
  child_user_id uuid not null references auth.users(id) on delete cascade,
  child_display_name text not null default '',
  guardian_email text not null,
  consent_version text not null,
  status text not null default 'pending' check (status in ('pending','accepted','declined','withdrawn','superseded')),
  guardian_user_id uuid references auth.users(id) on delete set null,
  requested_at timestamptz not null default now(),
  accepted_at timestamptz,
  withdrawn_at timestamptz,
  updated_at timestamptz not null default now()
);
create unique index if not exists guardian_consent_one_active_idx
  on public.guardian_consent_requests(child_user_id)
  where status in ('pending','accepted');
create index if not exists guardian_consent_email_idx
  on public.guardian_consent_requests(lower(guardian_email));

create table if not exists public.guardian_consent_log (
  id bigint generated by default as identity primary key,
  child_user_id uuid not null references auth.users(id) on delete cascade,
  guardian_user_id uuid references auth.users(id) on delete set null,
  guardian_email text not null,
  action text not null check (action in ('accepted','declined','withdrawn','requested')),
  consent_version text not null,
  occurred_at timestamptz not null default now()
);

alter table public.guardian_consent_requests enable row level security;
alter table public.guardian_consent_log enable row level security;

drop policy if exists "guardian_request_child_read" on public.guardian_consent_requests;
create policy "guardian_request_child_read" on public.guardian_consent_requests
for select to authenticated using (child_user_id = auth.uid());

drop policy if exists "guardian_request_guardian_read" on public.guardian_consent_requests;
create policy "guardian_request_guardian_read" on public.guardian_consent_requests
for select to authenticated
using (lower(guardian_email) = lower(coalesce(auth.jwt() ->> 'email','')));

drop policy if exists "guardian_log_child_read" on public.guardian_consent_log;
create policy "guardian_log_child_read" on public.guardian_consent_log
for select to authenticated using (child_user_id = auth.uid());

drop policy if exists "guardian_log_guardian_read" on public.guardian_consent_log;
create policy "guardian_log_guardian_read" on public.guardian_consent_log
for select to authenticated
using (lower(guardian_email) = lower(coalesce(auth.jwt() ->> 'email','')));

revoke all on table public.guardian_consent_requests from anon, authenticated;
revoke all on table public.guardian_consent_log from anon, authenticated;
grant select on table public.guardian_consent_requests to authenticated;
grant select on table public.guardian_consent_log to authenticated;

-- 3) Account-level data-access guard. Student learning history is disabled until age is verified,
-- and for under-16 students until guardian consent has been verified.
create or replace function public.edutest_data_access_allowed(p_uid uuid)
returns boolean
language sql stable security definer set search_path = ''
as $$
  select exists (
    select 1 from public.profiles p
    where p.id = p_uid
      and p.deletion_requested_at is null
      and (
        p.role <> 'student'
        or (
          p.birth_date is not null
          and (
            p.birth_date <= (current_date - interval '16 years')::date
            or p.guardian_verified_at is not null
          )
        )
      )
  );
$$;
revoke all on function public.edutest_data_access_allowed(uuid) from public;
grant execute on function public.edutest_data_access_allowed(uuid) to authenticated;

-- 4) Learning history tables and RLS.
create table if not exists public.question_history (
  user_id uuid not null references auth.users(id) on delete cascade,
  question_id text not null,
  seen_count integer not null default 0 check (seen_count >= 0),
  correct_count integer not null default 0 check (correct_count >= 0),
  wrong_count integer not null default 0 check (wrong_count >= 0),
  last_seen timestamptz,
  last_correct timestamptz,
  last_wrong timestamptz,
  last_test_id text,
  last_pool text,
  updated_at timestamptz not null default now(),
  primary key (user_id, question_id)
);
create index if not exists question_history_user_last_seen_idx on public.question_history(user_id,last_seen desc);

create table if not exists public.subject_history (
  user_id uuid not null references auth.users(id) on delete cascade,
  pool_key text not null,
  sessions integer not null default 0 check (sessions >= 0),
  total_pct integer not null default 0 check (total_pct >= 0),
  diff smallint not null default 1 check (diff between 0 and 2),
  last_session_at timestamptz,
  updated_at timestamptz not null default now(),
  primary key (user_id,pool_key)
);

alter table public.question_history enable row level security;
alter table public.subject_history enable row level security;

-- Recreate all learning-history policies with the child-consent access guard.
do $$
declare pol record;
begin
  for pol in select policyname from pg_policies where schemaname='public' and tablename='question_history' loop
    execute format('drop policy if exists %I on public.question_history',pol.policyname);
  end loop;
  for pol in select policyname from pg_policies where schemaname='public' and tablename='subject_history' loop
    execute format('drop policy if exists %I on public.subject_history',pol.policyname);
  end loop;
end $$;

create policy "question_history_select_own" on public.question_history for select to authenticated
using (auth.uid()=user_id and public.edutest_data_access_allowed(auth.uid()));
create policy "question_history_insert_own" on public.question_history for insert to authenticated
with check (auth.uid()=user_id and public.edutest_data_access_allowed(auth.uid()));
create policy "question_history_update_own" on public.question_history for update to authenticated
using (auth.uid()=user_id and public.edutest_data_access_allowed(auth.uid()))
with check (auth.uid()=user_id and public.edutest_data_access_allowed(auth.uid()));
create policy "question_history_delete_own" on public.question_history for delete to authenticated
using (auth.uid()=user_id and public.edutest_data_access_allowed(auth.uid()));

create policy "subject_history_select_own" on public.subject_history for select to authenticated
using (auth.uid()=user_id and public.edutest_data_access_allowed(auth.uid()));
create policy "subject_history_insert_own" on public.subject_history for insert to authenticated
with check (auth.uid()=user_id and public.edutest_data_access_allowed(auth.uid()));
create policy "subject_history_update_own" on public.subject_history for update to authenticated
using (auth.uid()=user_id and public.edutest_data_access_allowed(auth.uid()))
with check (auth.uid()=user_id and public.edutest_data_access_allowed(auth.uid()));
create policy "subject_history_delete_own" on public.subject_history for delete to authenticated
using (auth.uid()=user_id and public.edutest_data_access_allowed(auth.uid()));

revoke all on table public.question_history from anon, authenticated;
revoke all on table public.subject_history from anon, authenticated;
grant select,insert,update,delete on table public.question_history to authenticated;
grant select,insert,update,delete on table public.subject_history to authenticated;

-- 5) Create/update profile on Auth signup and create under-16 guardian request server-side.
create or replace function public.handle_edutest_new_user()
returns trigger
language plpgsql security definer set search_path = ''
as $$
declare
  v_role text;
  v_birth date;
  v_guardian text;
  v_consent_version text;
begin
  begin
    v_birth := nullif(new.raw_user_meta_data ->> 'birth_date','')::date;
  exception when others then
    v_birth := null;
  end;
  v_guardian := lower(trim(coalesce(new.raw_user_meta_data ->> 'guardian_email','')));
  v_consent_version := coalesce(nullif(new.raw_user_meta_data ->> 'guardian_consent_version',''),'guardian-consent-v1');
  v_role := case
    when new.raw_user_meta_data ->> 'requested_role' = 'teacher' then 'pending_teacher'
    when new.raw_user_meta_data ->> 'requested_role' = 'guardian' then 'guardian'
    else 'student'
  end;

  insert into public.profiles(
    id,email,name,role,grade,school,birth_date,guardian_email,
    terms_version,terms_accepted_at,privacy_version,privacy_acknowledged_at,last_active_at
  ) values (
    new.id,new.email,coalesce(new.raw_user_meta_data ->> 'name',''),v_role,
    coalesce(new.raw_user_meta_data ->> 'grade',''),coalesce(new.raw_user_meta_data ->> 'school',''),
    v_birth,nullif(v_guardian,''),
    nullif(new.raw_user_meta_data ->> 'terms_version',''),now(),
    nullif(new.raw_user_meta_data ->> 'privacy_version',''),now(),now()
  )
  on conflict (id) do update set
    email=excluded.email,name=excluded.name,grade=excluded.grade,school=excluded.school,
    birth_date=coalesce(public.profiles.birth_date,excluded.birth_date),
    guardian_email=coalesce(public.profiles.guardian_email,excluded.guardian_email),
    updated_at=now();

  if v_role='student' and v_birth is not null and v_birth > (current_date - interval '16 years')::date then
    if v_guardian='' then
      raise exception 'Guardian email is required for a student under 16';
    end if;
    insert into public.guardian_consent_requests(child_user_id,child_display_name,guardian_email,consent_version,status)
    values(new.id,coalesce(new.raw_user_meta_data ->> 'name',''),v_guardian,v_consent_version,'pending')
    on conflict do nothing;
    insert into public.guardian_consent_log(child_user_id,guardian_email,action,consent_version)
    values(new.id,v_guardian,'requested',v_consent_version);
  end if;
  return new;
end;
$$;
revoke all on function public.handle_edutest_new_user() from public;

drop trigger if exists on_auth_user_created_edutest on auth.users;
create trigger on_auth_user_created_edutest after insert on auth.users
for each row execute function public.handle_edutest_new_user();

-- 6) Existing/legacy students must complete age verification before learning history is available.
create or replace function public.complete_age_verification(
  p_birth_date date,
  p_guardian_email text,
  p_terms_version text,
  p_privacy_version text,
  p_guardian_consent_version text
) returns jsonb
language plpgsql security definer set search_path = ''
as $$
declare
  v_uid uuid := auth.uid();
  v_under16 boolean;
  v_email text := lower(trim(coalesce(p_guardian_email,'')));
  v_name text;
begin
  if v_uid is null then raise exception 'Authentication required'; end if;
  if p_birth_date is null or p_birth_date > current_date or p_birth_date < date '1900-01-01' then
    raise exception 'Invalid birth date';
  end if;
  select name into v_name from public.profiles where id=v_uid and role='student';
  if not found then raise exception 'Student profile not found'; end if;
  v_under16 := p_birth_date > (current_date - interval '16 years')::date;
  if v_under16 and (v_email='' or v_email=lower(coalesce(auth.jwt()->>'email',''))) then
    raise exception 'A different guardian email is required for a student under 16';
  end if;

  update public.profiles set
    birth_date=p_birth_date,
    guardian_email=case when v_under16 then v_email else null end,
    guardian_verified_at=case when v_under16 then null else guardian_verified_at end,
    terms_version=p_terms_version,terms_accepted_at=now(),
    privacy_version=p_privacy_version,privacy_acknowledged_at=now(),
    updated_at=now(),last_active_at=now()
  where id=v_uid;

  if v_under16 then
    update public.guardian_consent_requests set status='superseded',updated_at=now()
      where child_user_id=v_uid and status='pending';
    insert into public.guardian_consent_requests(child_user_id,child_display_name,guardian_email,consent_version,status)
      values(v_uid,v_name,v_email,p_guardian_consent_version,'pending');
    insert into public.guardian_consent_log(child_user_id,guardian_email,action,consent_version)
      values(v_uid,v_email,'requested',p_guardian_consent_version);
  end if;
  return jsonb_build_object('under16',v_under16,'guardian_email',case when v_under16 then v_email else null end);
end;
$$;
revoke all on function public.complete_age_verification(date,text,text,text,text) from public;
grant execute on function public.complete_age_verification(date,text,text,text,text) to authenticated;

-- 7) Guardian acceptance / decline / withdrawal. The guardian must be authenticated as the same email
-- that the child supplied; acceptance time is server-generated.
create or replace function public.accept_guardian_consent(p_child_user_id uuid,p_consent_version text)
returns boolean
language plpgsql security definer set search_path = ''
as $$
declare
  v_guardian_uid uuid := auth.uid();
  v_guardian_email text := lower(coalesce(auth.jwt()->>'email',''));
  v_req public.guardian_consent_requests%rowtype;
begin
  if v_guardian_uid is null or v_guardian_email='' then raise exception 'Authentication required'; end if;
  select * into v_req from public.guardian_consent_requests
   where child_user_id=p_child_user_id
     and lower(guardian_email)=v_guardian_email
     and status='pending'
   order by requested_at desc limit 1 for update;
  if not found then raise exception 'No matching pending guardian-consent request'; end if;
  if v_req.consent_version <> p_consent_version then raise exception 'Consent text version mismatch'; end if;

  update public.guardian_consent_requests set status='accepted',guardian_user_id=v_guardian_uid,
    accepted_at=now(),updated_at=now() where id=v_req.id;
  update public.profiles set guardian_verified_at=now(),updated_at=now() where id=p_child_user_id;
  insert into public.guardian_consent_log(child_user_id,guardian_user_id,guardian_email,action,consent_version)
    values(p_child_user_id,v_guardian_uid,v_guardian_email,'accepted',p_consent_version);
  return true;
end;
$$;
revoke all on function public.accept_guardian_consent(uuid,text) from public;
grant execute on function public.accept_guardian_consent(uuid,text) to authenticated;

create or replace function public.decline_guardian_consent(p_child_user_id uuid,p_consent_version text)
returns boolean
language plpgsql security definer set search_path = ''
as $$
declare
  v_uid uuid:=auth.uid(); v_email text:=lower(coalesce(auth.jwt()->>'email',''));
  v_req public.guardian_consent_requests%rowtype;
begin
  select * into v_req from public.guardian_consent_requests
   where child_user_id=p_child_user_id and lower(guardian_email)=v_email and status='pending'
   order by requested_at desc limit 1 for update;
  if not found then raise exception 'No matching pending guardian-consent request'; end if;
  if v_req.consent_version<>p_consent_version then raise exception 'Consent text version mismatch'; end if;
  update public.guardian_consent_requests set status='declined',guardian_user_id=v_uid,updated_at=now() where id=v_req.id;
  insert into public.guardian_consent_log(child_user_id,guardian_user_id,guardian_email,action,consent_version)
    values(p_child_user_id,v_uid,v_email,'declined',p_consent_version);
  return true;
end;
$$;
revoke all on function public.decline_guardian_consent(uuid,text) from public;
grant execute on function public.decline_guardian_consent(uuid,text) to authenticated;

create or replace function public.withdraw_guardian_consent(p_child_user_id uuid,p_consent_version text)
returns boolean
language plpgsql security definer set search_path = ''
as $$
declare
  v_uid uuid:=auth.uid(); v_email text:=lower(coalesce(auth.jwt()->>'email',''));
  v_req public.guardian_consent_requests%rowtype;
begin
  select * into v_req from public.guardian_consent_requests
   where child_user_id=p_child_user_id and lower(guardian_email)=v_email and status='accepted'
   order by accepted_at desc limit 1 for update;
  if not found then raise exception 'No matching accepted guardian consent'; end if;
  update public.guardian_consent_requests set status='withdrawn',withdrawn_at=now(),updated_at=now() where id=v_req.id;
  update public.profiles set guardian_verified_at=null,updated_at=now() where id=p_child_user_id;
  insert into public.guardian_consent_log(child_user_id,guardian_user_id,guardian_email,action,consent_version)
    values(p_child_user_id,v_uid,v_email,'withdrawn',p_consent_version);
  return true;
end;
$$;
revoke all on function public.withdraw_guardian_consent(uuid,text) from public;
grant execute on function public.withdraw_guardian_consent(uuid,text) to authenticated;

-- 8) Activity + deletion-request RPCs.
create or replace function public.touch_edutest_activity()
returns void language sql security definer set search_path=''
as $$ update public.profiles set last_active_at=now(),updated_at=now() where id=auth.uid(); $$;
revoke all on function public.touch_edutest_activity() from public;
grant execute on function public.touch_edutest_activity() to authenticated;

create or replace function public.request_account_deletion()
returns timestamptz language plpgsql security definer set search_path=''
as $$
declare v timestamptz:=now(); begin
  update public.profiles set deletion_requested_at=v,updated_at=v where id=auth.uid();
  delete from public.question_history where user_id=auth.uid();
  delete from public.subject_history where user_id=auth.uid();
  return v;
end; $$;
revoke all on function public.request_account_deletion() from public;
grant execute on function public.request_account_deletion() to authenticated;

-- 9) Retention helper for application data. Schedule daily with Supabase Cron if desired.
-- Auth-user deletion must be done server-side (see included delete-account Edge Function).
create or replace function public.edutest_retention_cleanup()
returns table(question_rows_deleted bigint,subject_rows_deleted bigint,pending_requests_expired bigint)
language plpgsql security definer set search_path=''
as $$
declare qn bigint:=0; sn bigint:=0; gn bigint:=0;
begin
  delete from public.question_history q
    using public.profiles p
    where q.user_id=p.id and p.last_active_at < now()-interval '24 months';
  get diagnostics qn = row_count;
  delete from public.subject_history s
    using public.profiles p
    where s.user_id=p.id and p.last_active_at < now()-interval '24 months';
  get diagnostics sn = row_count;
  update public.guardian_consent_requests
    set status='superseded',updated_at=now()
    where status='pending' and requested_at < now()-interval '30 days';
  get diagnostics gn = row_count;
  return query select qn,sn,gn;
end; $$;
revoke all on function public.edutest_retention_cleanup() from public;

commit;

-- IMPORTANT PRODUCTION CONFIGURATION
-- 1. Deploy the included `delete-account` Edge Function; it uses a server-side secret/service role.
-- 2. Configure custom SMTP, SPF/DKIM/DMARC, email confirmation, CAPTCHA/rate limits.
-- 3. Fill the legal controller identity/contact and actual Supabase project region in the HTML config.
-- 4. Schedule public.edutest_retention_cleanup() daily using Supabase Cron (server-side), if enabled.
-- 5. Admin accounts should use MFA/AAL2 and must never be created/promoted from browser code.
